import { dirNames, fileNames } from "../../constants/index.js";
import { toAllScriptEndings, toPosix } from "../fs/index.js";
import type { Chunk } from "client:page";
import fs from "node:fs/promises";
import path from "node:path";
import type { Manifest, ManifestChunk } from "vite";

let manifestCache: Promise<Manifest> | undefined;
const chunkCache = new Map<string, Promise<Chunk>>();

/**
 * @returns new or cached client `Manifest`
 */
const getManifest = async () => {
	if (!manifestCache) {
		manifestCache = fs
			.readFile(
				path.join(
					dirNames.out.base,
					dirNames.out.client.base,
					".vite",
					"manifest.json",
				),
				"utf-8",
			)
			.then((str) => JSON.parse(str) as Manifest)
			.catch((error) => {
				manifestCache = undefined;
				throw error;
			});
	}

	return manifestCache;
};

/**
 * Resolves an entry chunk with direct manifest lookups.
 *
 * @param manifest Vite client manifest.
 * @param pathName Route path.
 * @param type Entry type.
 * @returns Matching manifest chunk, if present.
 */
export const resolveChunk = (
	manifest: Manifest,
	pathName: string,
	type: "page" | "script" | "style",
) => {
	const srcPath = toPosix(
		path.join(
			dirNames.src.client,
			pathName,
			type === "page"
				? fileNames.page
				: type === "script"
					? fileNames.script
					: fileNames.style,
		),
	);

	if (type !== "script") return manifest[srcPath];

	for (const id of toAllScriptEndings(srcPath)) {
		if (manifest[id]) return manifest[id];
	}
};

/**
 * Reads the manifest generated by the client build and creates
 * a string of <script> `tags` and `src` paths based on the
 * imports/hashed names.
 *
 * @param options
 * @returns The HTML <script> tags as a concatenated string and `src` paths.
 */
export const getChunk = (options: {
	/** @example "/react" */
	pathName: string;

	/** Pass through Vite plugin `this.error` */
	error: (message: string) => never;

	/**
	 * If the pathname is an import. If so, it already is the full name.
	 * So there is no need to check the manifest for all the endings, we
	 * know it's already there.
	 */
	imp?: boolean;

	/** Type of the entry point. */
	type: "page" | "script" | "style";
}): Promise<Chunk> => {
	const key = `${options.imp ? "import" : options.type}:${options.pathName}`;
	const cached = chunkCache.get(key);
	if (cached) return cached;

	const chunk = createChunk(options);
	chunkCache.set(key, chunk);
	chunk.catch(() => chunkCache.delete(key));

	return chunk;
};

const createChunk = async ({
	pathName,
	error,
	imp = false,
	type,
}: {
	/** @example "/react" */
	pathName: string;

	/** Pass through Vite plugin `this.error` */
	error: (message: string) => never;

	/**
	 * If the pathname is an import. If so, it already is the full name.
	 * So there is no need to check the manifest for all the endings, we
	 * know it's already there.
	 */
	imp?: boolean;

	/** Type of the entry point. */
	type: "page" | "script" | "style";
}): Promise<Chunk> => {
	const manifest = await getManifest();
	const manifestChunk: ManifestChunk | undefined = imp
		? manifest[pathName]
		: resolveChunk(manifest, pathName, type);

	const chunk: Chunk = {
		tags: "",
		src: {
			src: "",
			file: "",
			module: [],
			preload: [],
			style: [],
			assets: [],
			dynamic: [],
		},
	};

	if (!manifestChunk) {
		error(`No tags found in manifest for \`${pathName}\``);
		return chunk;
	}

	chunk.src.src = manifestChunk.src ?? "";
	chunk.src.file = manifestChunk.file;

	if (!imp) {
		// the entry file name
		if (type === "style") {
			chunk.tags += `<link rel="stylesheet" href="/${manifestChunk.file}">`;
			chunk.src.style.push("/" + manifestChunk.file);
		} else {
			chunk.tags += `<script type="module" src="/${manifestChunk.file}"></script>`;
			chunk.src.module.push("/" + manifestChunk.file);
		}
	} else {
		// a modulepreload link to get the script ready but don't execute immediately
		// this is required to flatten the request waterfall if you are using manual chunks for example
		chunk.tags += `<link rel="modulepreload" crossorigin href="/${manifestChunk.file}">`;
		chunk.src.preload.push("/" + manifestChunk.file);
	}

	if (manifestChunk.css) {
		// need to also do this for `imports` since css does not actually link in the code
		for (const cssFile of manifestChunk.css) {
			chunk.tags += `<link rel="stylesheet" href="/${cssFile}">`;
			chunk.src.style.push("/" + cssFile);
		}
	}

	if (manifestChunk.assets) {
		chunk.src.assets.push(...manifestChunk.assets);
	}

	const [dynamicChunks, importChunks] = await Promise.all([
		// Only add dynamic imports from entry points to avoid infinite loops.
		// https://github.com/rossrobino/domco/issues/93
		Promise.all(
			(!imp ? (manifestChunk.dynamicImports ?? []) : []).map((impPathName) =>
				getChunk({ pathName: impPathName, imp: true, error, type: "script" }),
			),
		),
		Promise.all(
			(manifestChunk.imports ?? []).map((impPathName) =>
				getChunk({ pathName: impPathName, imp: true, error, type: "script" }),
			),
		),
	]);

	// Dynamic chunks are not added to tags or flattened. Consumers may not want
	// to request them unless they are truly needed.
	chunk.src.dynamic.push(...dynamicChunks);

	for (const impChunk of importChunks) {
		chunk.tags += impChunk.tags;
		chunk.src.module.push(...impChunk.src.module);
		chunk.src.preload.push(...impChunk.src.preload);
		chunk.src.style.push(...impChunk.src.style);
		chunk.src.assets.push(...impChunk.src.assets);
		chunk.src.dynamic.push(...impChunk.src.dynamic);
	}

	return chunk;
};

/**
 * @param chunk
 * @returns string of module code with `tags` and `src`
 */
export const getModule = (chunk: Chunk) => {
	return (
		`export const tags = ${JSON.stringify(chunk.tags)};\n` +
		`export const src = ${JSON.stringify(chunk.src)};\n`
	);
};
